FROM php:8.1.13-fpm-alpine3.16

# When using node:16-alpine3.16 we have to run this:
RUN apk add yarn

WORKDIR /usr/src/app

COPY package*.json ./

#RUN npm ci
RUN yarn install --frozen-lockfile --no-progress --non-interactive --link-duplicates

COPY . .

CMD [ "npm", "start" ]
