FROM php:8.1.13-fpm-alpine3.16

RUN apk add yarn python3

WORKDIR /usr/src/app

COPY package*.json ./

RUN yarn install --frozen-lockfile --no-progress --non-interactive --link-duplicates

COPY . .

CMD [ "npm", "start" ]
