FROM node:16-alpine3.16

# This is a known diff, we install some additional packages manually
RUN apk add yarn
#python3 make g++

WORKDIR /usr/src/app

COPY package*.json ./

RUN yarn install --frozen-lockfile --no-progress --non-interactive --link-duplicates

COPY . .

CMD [ "npm", "start" ]
